services:
    Nemoneph\SipsPlugin\Form\SipsGatewayConfigurationType:
        tags:
            - { name: sylius.gateway_configuration_type, type: atos_sips, label: atos_sips }
            - { name: form.type }


    Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder:
        arguments: [Nemoneph\SipsPlugin\SipsGatewayFactory]
        tags:
            - { name: payum.gateway_factory_builder, factory: atos_sips }



